# 넘파이 사용법 확인

### 기본사용법 패키지 추가
#### 설치
> pip install numpy

### Numpy 버전확인

In [1]:
import numpy as np
print(np.__version__)


1.21.4


### np.array()

In [5]:
# 1차원 배열
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# 2차원 배열
mat = np.array([[10,20,30],[40,50,60]])
print(mat)

[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [7]:
# 배열의 타입확인
print(f'arr의 타입 : {type(arr)}')
print(f'mat의 타입 : {type(mat)}')

# 배열의 축(ndim)과 크기(shape) 확인
print(f'arr의 축 : {arr.ndim}')
print(f'arr의 크기 : {arr.shape}')
print(f'mat의 축 : {mat.ndim}')
print(f'mat의 크기 : {mat.shape}')



arr의 타입 : <class 'numpy.ndarray'>
mat의 타입 : <class 'numpy.ndarray'>
arr의 축 : 1
arr의 크기 : (5,)
mat의 축 : 2
mat의 크기 : (2, 3)


In [12]:
#ndarray 초기화 방법
mat_zero = np.zeros([2, 3])
print(mat_zero)

mat_one = np.ones([2, 3])
print(mat_one)

mat_eight = np.full([2, 3], 8)
print(mat_eight)

mat_eye = np.eye(3)
print(mat_eye)

mat_rand = np.random.random([2,3])
print(mat_rand)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8]
 [8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.60401332 0.87922728 0.81235333]
 [0.83359204 0.20594759 0.62276732]]


### 다양한 기능 메서드

In [8]:
# np.arrange
import numpy as np

# 0부터 9까지
arr_range = np.arange(10)
print(arr_range)

# 1부터 50까지 4씩 증가하는 배열
arr_fourtime_to_fifty = np.arange(1, 51, 4)
print(arr_fourtime_to_fifty)

# 0~11 까지 1차원배열
array = np.arange(12)
print(array)
arr_reshape = np.array(array).reshape([3,4])
print(arr_reshape)

# 슬라이싱
slice_row = arr_reshape[0, :]
print(slice_row)

# 두번째 열 슬라이싱
slice_col = arr_reshape[:, 1]
print(slice_col)

[0 1 2 3 4 5 6 7 8 9]
[ 1  5  9 13 17 21 25 29 33 37 41 45 49]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[1 5 9]


In [28]:
# 인덱싱으로 새로운 배열 생성
arr_ind = arr_reshape[[0, 1], [1, 3]]
print(arr_ind)

d = np.array([arr_reshape[0, 1], arr_reshape[1, 3], arr_reshape[2, 3]])
print(d)

[1 7]
[ 1  7 11]


### Numpy 연산

In [29]:
## 연산
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))

mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
print(np.dot(mat1, mat2))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[[19 22]
 [43 50]]
