# 판다스 사용법 따라가기

### 기본 사용법 - 패키지 사용 추가

In [1]:
# 판다스 패키지 추가
import pandas as pd

pd.__version__

'1.3.5'

### 시리즈 타입

In [7]:
import pandas as pd
import numpy as np

data = list(range(101, 106))
series1 = pd.Series(data)
print(f'series1 =>\n{series1}')

arr1 = np.array(data)
series2 = pd.Series(arr1)
print(f'series2 =>\n{series2}')

arr2 = np.arange(101, 106)
series3 = pd.Series(arr2)
print(f'series3 =>\n{series3}')

series1 =>
0    101
1    102
2    103
3    104
4    105
dtype: int64
series2 =>
0    101
1    102
2    103
3    104
4    105
dtype: int32
series3 =>
0    101
1    102
2    103
3    104
4    105
dtype: int32


### 시리즈 다시

In [8]:
series4 = pd.Series([32000, 20000, 2000, 4500], index=['피자', '치킨', '콜라', '맥주'])
print('시리즈4 출력 ')
print('-'*20)
print(series4)

시리즈4 출력 
--------------------
피자    32000
치킨    20000
콜라     2000
맥주     4500
dtype: int64


In [11]:
print(f'시리즈4 값 : {series4.values}')
print(f'시리즈4 인덱스 : {series4.index}')
print(series4[1])

시리즈4 값 : [32000 20000  2000  4500]
시리즈4 인덱스 : Index(['피자', '치킨', '콜라', '맥주'], dtype='object')
20000


### 데이터프레임

In [12]:
values = [[1,2,3], [4,5,6], [7,8,9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values, index=index, columns=columns)

print('데이터프레임 출력 ')
print('-'*20)
print(df)

데이터프레임 출력 
--------------------
       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9


In [13]:
print('데이터프레임 인덱스 : {}'.format(df.index))
print('데이터프레임 열이름: {}'.format(df.columns))
print('데이터프레임 값 ')
print('-'*20)
print(df.values)

데이터프레임 인덱스 : Index(['one', 'two', 'three'], dtype='object')
데이터프레임 열이름: Index(['A', 'B', 'C'], dtype='object')
데이터프레임 값 
--------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 데이터프레임 생성

In [19]:
# 리스트로부터 생성
data = [
    ['1001', '홍길동', 97.72],
    ['1002', '성영곤', 100.00],
    ['1003', '홍길순', 64.20],
    ['1004', '장필순', 82.30],
    ['1005', '구덕임', 78.09]
]

df = pd.DataFrame(data)
print('학점 ')
print('-'*20)
print(df)

학점 
--------------------
      0    1       2
0  1001  홍길동   97.72
1  1002  성영곤  100.00
2  1003  홍길순   64.20
3  1004  장필순   82.30
4  1005  구덕임   78.09


In [20]:
df = pd.DataFrame(data, columns=['학번', '이름', '점수'])
print(df)

     학번   이름      점수
0  1001  홍길동   97.72
1  1002  성영곤  100.00
2  1003  홍길순   64.20
3  1004  장필순   82.30
4  1005  구덕임   78.09


In [21]:
# 딕셔너리
data2 = {
    '학번': ['1001','1002','1003','1004','1005'],
    '이름': ['홍길동','성영곤','홍길순','장필순','구덕임'],
    '점수':[97.72, 100.00, 64.20, 82.30, 78.09]
}

df2 = pd.DataFrame(data2)
print(df2)

     학번   이름      점수
0  1001  홍길동   97.72
1  1002  성영곤  100.00
2  1003  홍길순   64.20
3  1004  장필순   82.30
4  1005  구덕임   78.09


### 데이터프레임 조회

In [24]:
# 앞부분 2개만 조회
print(df.head(2))
# 뒷부분 3개만 조회
print(df.tail(3))
# 학번에 대한 열만 보기
print(df['학번'])

     학번   이름      점수
0  1001  홍길동   97.72
1  1002  성영곤  100.00
     학번   이름     점수
2  1003  홍길순  64.20
3  1004  장필순  82.30
4  1005  구덕임  78.09
0    1001
1    1002
2    1003
3    1004
4    1005
Name: 학번, dtype: object


#### 외부데이터 읽어오기

In [26]:
df = pd.read_csv('sample.csv')
print(df)
print(df.index)

     학번   이름     점수
0  1001  홍길동  97.62
1  1002  성영곤  99.99
2  1003  홍길순  63.20
3  1004  장필순  81.10
RangeIndex(start=0, stop=4, step=1)
